baseURL = "https://mjpitz.com/"
languageCode = "en-us"
title = "Mya Pitzeruse"
theme = "anatole"
enableRobotsTXT = true


# Highlighting config
pygmentsCodeFences = true
pygmentsUseClasses = false
# Use the new Chroma Go highlighter in Hugo.
pygmentsUseClassic = false
pygmentsOptions = "linenos=table"
# See https://help.farbox.com/pygments.html
pygmentsStyle = "tango"

# Google Analytics
googleAnalytics = "UA-39314903-5"

[permalinks]
blog = "/blog/:year/:month/:day/:slug/"
media = "/media/:year/:month/:day/:slug/"

[params]
title = "Mya Pitzeruse"
author = "Mya Pitzeruse"
description = ""
profilePicture = "/statics/img/mjpitz.jpeg"
keywords = ""
favicon = "statics/img/"
customCss = [ "statics/css/overrides.css" ]
mainSections = ["blog", "media"]

## Math settings
[params.math]
enable = false  # options: true, false. Enable math support globally, default: false. You can always enable math on per page.
use = "katex"  # options: "katex", "mathjax". default is "katex".

## Social links

[[params.socialIcons]]
icon = "fa-github"
title = "GitHub"
url = "https://github.com/mjpitz"

[[params.socialIcons]]
icon = "fa-twitter"
title = "Twitter"
url = "https://twitter.com/myajpitz"

[[params.socialIcons]]
icon = "fa-linkedin"
title = "LinkedIn"
url = "https://www.linkedin.com/in/mjpitz/"

[[params.socialIcons]]
icon = "fa-rss"
title = "Feed"
url = "/index.xml"

## Menu items

[menu]

  [[menu.main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[menu.main]]
  name = "Media"
  identifier = "media"
  weight = 200
  url = "/media/"

  [[menu.main]]
  name = "Blog"
  weight = 500
  identifier = "blog"
  url = "/blog/"
